version: "3.9"

services:

  redis:
    image: redis

  wmui/express-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
